version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "ci: "
      include: "scope"
    groups:
      github-actions-updates:
        patterns:
          - "*"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: ".devcontainer"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "build: "
      include: "scope"
    groups:
      docker-updates:
        patterns:
          - "*"
